import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/customComponents/Navbar";
import Footer from "./home/(components)/Footer";

const JostFont = Jost({
  variable: "--font-josh",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${JostFont.variable}   bg-gray-50  antialiased max-w-screen    overflow-x-hidden `}
      >
        <Navbar />
        <main className="min-h-[50vh]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
