import type { Metadata } from "next";
import "./globals.css";
import { Jost } from "next/font/google";
import { Provider } from "@/components/ui/provider";

const JostFont = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${JostFont.variable}`}>
      <body className="antialiased">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
