version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: skillbazzar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend # Assuming you have a backend folder with Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/skillbazzar

  frontend:
    build: ./frontend # Assuming you have a frontend folder with Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
